runtime: go120  # ou a versão do Go que você está usando
env_variables:
  ENV: "production"
  PORT: "8080"  # App Engine geralmente usa porta 8080
  DB_HOST: "seu-host-db"
  DB_USER: "seu-usuario"
  DB_DSN: "usuario:senha@tcp(host:3306)/nome-do-banco"